version: 2
jobs:
  build:
    docker:
      - image: csmcallister/fbo-scraper-test-image
      - image: circleci/postgres:9.6.8
        environment:
          - POSTGRES_USER=circleci
          - POSTGRES_DB=smartie-test
    steps:
      - checkout
      - run: python -m unittest test.py
      - store_artifacts:
          path: test-reports
          destination: test-reports
