version: 2
jobs:
  build:
    docker:
      - image: csmcallister/fbo-scraper-test
      - image: circleci/postgres:9.6.8
        environment:
          - POSTGRES_USER: circleci
          - POSTGRES_DB: smartie-test
    steps:
      - checkout
      - run:
          name: Waiting for Postgres to be ready
          command: |
            for i in `seq 1 50`;
            do
              nc -z localhost 5432 && echo Success && exit 0
              echo -n .
              sleep 1
            done
            echo Failed waiting for Postgres && exit 1
      - run:
          name: Run tests
          environment:
            TEST_DB_URL: "postgres://circleci@localhost:5432/smartie-test?sslmode=disable"
          command: python3 -W ignore -m unittest test.py
      - store_artifacts:
          path: test-reports
          destination: test-reports
