version: 2
jobs:
  build:
    docker:
      - image: csmcallister/fbo-scraper-test-image
    steps:
      - checkout
      - run: python -m unittest test.py
      - store_artifacts:
          path: test-reports
          destination: test-reports
