version: 2
jobs:
  build:
    docker:
      - image: csmcallister/fbo-scraper-test
      - image: circleci/postgres:9.6.8
        environment:
          - POSTGRES_USER: circleci
          - POSTGRES_DB: smartie-test
    steps:
      - checkout
      - run:
          name: Waiting for Postgres to be ready
          command: |
            for i in `seq 1 50`;
            do
              nc -z localhost 5432 && echo Success && exit 0
              echo -n .
              sleep 1
            done
            echo Failed waiting for Postgres && exit 1
      - run:
          name: Run tests
          environment:
            TEST_DB_URL: "postgres://circleci@localhost:5432/smartie-test?sslmode=disable"
          command: python -W ignore -m unittest discover tests -p '*_test.py'
  deploy:
    machine:
      enabled: true  
    steps:
      - checkout
      - run:
          name: Download CloudFoundry CLI
          command: |
            curl -v -L -o cf-cli_amd64.deb 'https://cli.run.pivotal.io/stable?release=debian64&source=github'
            sudo dpkg -i cf-cli_amd64.deb
            cf -v
            cf login -a https://api.fr.cloud.gov -u $SRT_FBO_SCRAPER_DEV_SERVICE_USERNAME -p $SRT_FBO_SCRAPER_DEV_SERVICE_PASSWORD -o gsa-ogp-srt -s dev
      - setup_remote_docker:   
          docker_layer_caching: true
      # TODO: use a primary image that already has Docker
      # here we install it during each build 
      - run:
          name: Install Docker client
          command: |
            set -x
            VER="18.06.0-ce"
            curl -L -o /tmp/docker-$VER.tgz https://download.docker.com/linux/static/stable/x86_64/docker-$VER.tgz
            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            mv /tmp/docker/* /usr/bin
      # build and push Docker image
      - run: |
          echo $CIRCLE_BRANCH
          TAG=0.1.$CIRCLE_BUILD_NUM
          docker build -t csmcallister/srt-fbo-scraper-$CIRCLE_BRANCH:$TAG .     
          docker login -u $DOCKER_USER -p $DOCKER_PASS
          docker push $DOCKER_USER/srt-fbo-scraper-$CIRCLE_BRANCH:$TAG

#workflows:
# version: 2
#  build-and-deploy:
#    jobs:
#      - build
#      - deploy:
#          requires:
#            - build
#          filters:
#            branches:
#              only: dev