version: 2
jobs:
  
  build:
    docker:
      - image: csmcallister/fbo-scraper-test
      - image: circleci/postgres:9.6.8
        environment:
          - POSTGRES_USER: circleci
          - POSTGRES_DB: smartie-test
    steps:
      - checkout
      - run:
          name: Waiting for Postgres to be ready
          command: |
            for i in `seq 1 50`;
            do
              nc -z localhost 5432 && echo Success && exit 0
              echo -n .
              sleep 1
            done
            echo Failed waiting for Postgres && exit 1
      - run:
          name: Run tests
          environment:
            TEST_DB_URL: "postgres://circleci@localhost:5432/smartie-test?sslmode=disable"
          command: python -W ignore -m unittest discover tests -p '*_test.py'
  
  deploy:
    docker:
      - image: circleci/buildpack-deps:jessie-curl
    steps:
      - checkout
      - setup_remote_docker:   
          docker_layer_caching: true
      - run: 
          name: Build and Push Docker Image
          command: |
            #use GitHub API to get name of PR's target branch
            PR_NUMBER="${CIRCLE_PULL_REQUEST//[!0-9]/}"
            TARGET_BRANCH=$(curl -sS https://api.github.com/repos/GSA/${CIRCLE_PROJECT_REPONAME}/pulls/${PR_NUMBER} | jq '.base.ref')
            TARGET_BRANCH=$(echo $TARGET_BRANCH | tr -d '"')
            if [ "$TARGET_BRANCH" = "master" ]
            then
                TARGET_BRANCH=prod
            else
                :
            fi
            TAG=0.1.$CIRCLE_BUILD_NUM
            #docker build, login and push
            docker build -t $DOCKER_USER/srt-fbo-scraper-$TARGET_BRANCH:$TAG . 
            echo "$DOCKER_PASS" | docker login --username $DOCKER_USER --password-stdin    
            docker push $DOCKER_USER/srt-fbo-scraper-$TARGET_BRANCH:$TAG
      - run:
          name: Download cf CLI and deploy
          command: |
            #use GitHub API to get name of PR's target branch (TODO make this DRY)
            PR_NUMBER="${CIRCLE_PULL_REQUEST//[!0-9]/}"
            TARGET_BRANCH=$(curl -sS https://api.github.com/repos/GSA/${CIRCLE_PROJECT_REPONAME}/pulls/${PR_NUMBER} | jq '.base.ref')
            TARGET_BRANCH=$(echo $TARGET_BRANCH | tr -d '"')
            if [ "$TARGET_BRANCH" = "master" ]
            then
                TARGET_BRANCH=prod
            else
                :
            fi
            #download CF CLI, login and push
            curl -v -L -o cf-cli_amd64.deb 'https://cli.run.pivotal.io/stable?release=debian64&source=github'
            sudo dpkg -i cf-cli_amd64.deb
            cf -v
            cf login -a https://api.fr.cloud.gov -u $CF_SERVICE_ACCOUNT -p $CF_SERVICE_PW -o gsa-ogp-srt -s $TARGET_BRANCH

            TAG=0.1.$CIRCLE_BUILD_NUM
            cf push srt-fbo-scraper-$TARGET_BRANCH --docker-image $DOCKER_USER/srt-fbo-scraper-$TARGET_BRANCH:$TAG -k 4G

workflows:
  version: 2
  build-and-deploy: 
    jobs:
      - build
      - hold:
          type: approval # requires in-app button be clicked to continue.
          requires:
           - build
      - deploy:
          requires:
            - hold